export const FundConfigs = {
  "008764": {
    name: "天弘越南市场股票(QDII)C(008764)",
    maxBoard: null,
    toCNY: 0.00027,
    stocks: [
      {
        label: "FPT公司",
        yahooCode: "FPT.VN",
        msnCode: "aqji2w",
        weight: 7.86,
      },
      {
        label: "和发集团",
        yahooCode: "HPG.VN",
        msnCode: "aqjkim",
        weight: 7.6,
      },
      {
        label: "移动世界投资公司",
        yahooCode: "MWG.VN",
        msnCode: "aqjooc",
        weight: 7.58,
      },
      {
        label: "越南繁荣银行",
        yahooCode: "VPB.VN",
        msnCode: "aqk1im",
        weight: 6.91,
      },
      {
        label: "军队股份制商业银行",
        yahooCode: "MBB.VN",
        msnCode: "aqjo77",
        weight: 6.37,
      },
      {
        label: "Vinhomes JSC",
        yahooCode: "VHM.VN",
        msnCode: "azztvh",
        weight: 6.15,
      },
      {
        label: "Masan Group Corp",
        yahooCode: "MSN.VN",
        msnCode: "aqjolh",
        weight: 5.2,
      },
      {
        label: "越南科技商业银行",
        yahooCode: "TCB.VN",
        msnCode: "b15bar",
        weight: 4.92,
      },
      {
        label: "越南工商股份制商业银行",
        yahooCode: "CTG.VN",
        msnCode: "aqjek2",
        weight: 4.64,
      },
      {
        label: "胡志明市发展股份制商业银行",
        yahooCode: "HDB.VN",
        msnCode: "ay6noc",
        weight: 4.1,
      },
    ],
  },
  "002010": {
    name: "中欧瑾通灵活配置混合C",
    maxBoard: 15.88 / 4.26,
    toCNY: 1,
    stocks: [
      {
        label: "中国平安",
        yahooCode: "",
        msnCode: "ad99yc",
        weight: 0.73,
      },
      {
        label: "中际旭创",
        yahooCode: "",
        msnCode: "adeku2",
        weight: 0.46,
      },
      {
        label: "中矿资源",
        yahooCode: "MWG.VN",
        msnCode: "add83m",
        weight: 0.44,
      },
      {
        label: "紫金矿业",
        yahooCode: "",
        msnCode: "ad9fww",
        weight: 0.42,
      },
      {
        label: "宁德时代",
        yahooCode: "",
        msnCode: "b1a977",
        weight: 0.41,
      },
      {
        label: "万华化学",
        yahooCode: "",
        msnCode: "ad7uqh",
        weight: 0.4,
      },
      {
        label: "阳光电源",
        yahooCode: "",
        msnCode: "adei2w",
        weight: 0.4,
      },
      {
        label: "华建新材",
        yahooCode: "",
        msnCode: "ad8smw",
        weight: 0.39,
      },
      {
        label: "中国中兔",
        yahooCode: "",
        msnCode: "ad9foc",
        weight: 0.31,
      },
      {
        label: "柳工",
        yahooCode: "",
        msnCode: "adas1h",
        weight: 0.3,
      },
    ],
  },
  "001204": {
    name: "东方红稳健精选混合C",
    maxBoard: 20.29 / 8.4,
    toCNY: 1,
    stocks: [
      {
        label: "中国平安",
        yahooCode: "",
        msnCode: "ad99yc",
        weight: 0.91,
      },
      {
        label: "瀚蓝环境",
        yahooCode: "",
        msnCode: "ad7vsm",
        weight: 0.9,
      },
      {
        label: "税友股份",
        yahooCode: "",
        msnCode: "c2efsm",
        weight: 0.88,
      },
      {
        label: "紫金矿业",
        yahooCode: "",
        msnCode: "ad9fww",
        weight: 0.87,
      },
      {
        label: "巨人网络",
        yahooCode: "",
        msnCode: "adct7w",
        weight: 0.84,
      },
      {
        label: "宁德时代",
        yahooCode: "",
        msnCode: "b1a977",
        weight: 0.83,
      },

      {
        label: "鱼跃医疗",
        yahooCode: "",
        msnCode: "adc2oc",
        weight: 0.82,
      },
      {
        label: "伊利股份",
        yahooCode: "",
        msnCode: "ad8yww",
        weight: 0.81,
      },
      {
        label: "华能国际",
        yahooCode: "",
        msnCode: "ad7akr",
        weight: 0.8,
      },
      {
        label: "分众传媒",
        yahooCode: "",
        msnCode: "adblzr",
        weight: 0.74,
      },
    ],
  },
};
